version: 0
metadata:
  name: Chunkify Task Graph
  description: Chunkify
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "bhearsum/python-test-runner"
      command:
        - "/bin/bash"
        - "-c"
        - "git clone {{ event.head.repo.url }} && cd chunkify && git checkout {{ event.head.repo.branch }} && tox -e py27"
    extra:
      github:
        env: true
        events:
          - push
          - pull_request.*
    metadata:
      name: Chunkify Pull Request
      description: Pull Request
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
